# .streamlit/config.toml
[theme]
primaryColor = "#0068B1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#111111"
font = "sans serif"
base = "light"   # ou "dark" si vous souhaitez un thème sombre

[server]
maxUploadSize = 200   # en Mo, ajustez selon vos besoins

[browser]
gatherUsageStats = false
